services:
  tkj-debug-env:
    #image: pico-ultimate:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tkj_hat_dev
    ports:
      - "8080:8080"
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev 
      - ../Project:/home/coder/project
    restart: unless-stopped