Vagrant.configure("2") do |config|
  # Base Image: Debian 12 (Bookworm)
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096" # GNOME needs at least 4GB to be happy
    vb.cpus = 2
    
    # Crucial for GNOME UI performance
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"] 
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive

    apt-get update
    apt-get install -y task-gnome-desktop x11-xserver-utils lightdm \
            build-essential git

    # 2. Install Pico Build Dependencies
    apt-get install -y python3 python3-pip python3-serial \
      usbutils clangd cmake ninja-build gdb-multiarch wget curl pkg-config \
      autoconf automake libtool texinfo gawk sudo libusb-1.0-0-dev libhidapi-dev \
      libftdi1-dev libjim-dev libudev-dev gcc-arm-none-eabi libnewlib-arm-none-eabi \
      libstdc++-arm-none-eabi-newlib picotool openocd

    # 3. Setup Pico SDK 2.2.0
    mkdir -p /home/vagrant/.pico-sdk/sdk
    if [ ! -d "/home/vagrant/.pico-sdk/sdk/2.2.0" ]; then
      git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git /home/vagrant/.pico-sdk/sdk/2.2.0
      cd /home/vagrant/.pico-sdk/sdk/2.2.0 && git checkout 2.2.0
    fi
    chown -R vagrant:vagrant /home/vagrant/.pico-sdk
    echo "export PICO_SDK_PATH=/home/vagrant/.pico-sdk/sdk/2.2.0" >> /home/vagrant/.bashrc

    # 4. USB / Udev rules for Pico
    curl -o /etc/udev/rules.d/60-openocd.rules https://raw.githubusercontent.com/raspberrypi/pico-setup/master/60-openocd.rules
    
    # 5. Auto-login setup (Optional, so you don't have to type password in the VM)
    echo "[Seat:*]\nautologin-user=vagrant\nautologin-user-timeout=0" > /etc/lightdm/lightdm.conf.d/01_autologin.conf
  SHELL
end